"""add project and copyright models

Revision ID: 20250218
Revises: 
Create Date: 2026-02-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250218'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # project 表
    op.create_table(
        'project',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=True),
        sa.Column('project_type', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('current_step', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('version', sa.String(length=20), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('subject_type', sa.String(length=20), nullable=False),
        sa.Column('subject_name', sa.String(length=100), nullable=True),
        sa.Column('subject_id_number', sa.String(length=50), nullable=True),
        sa.Column('development_method', sa.String(length=20), nullable=True),
        sa.Column('publication_status', sa.String(length=20), nullable=True),
        sa.Column('completion_date', sa.Date(), nullable=True),
        sa.Column('first_publication_date', sa.Date(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('external_system_id', sa.String(length=100), nullable=True),
        sa.Column('external_status', sa.String(length=50), nullable=True),
        sa.Column('external_updated_at', sa.DateTime(), nullable=True),
        sa.Column('completeness_score', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.create_index(op.f('ix_project_project_type'), 'project', ['project_type'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    
    # copyright_data 表
    op.create_table(
        'copyright_data',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('software_full_name', sa.String(length=100), nullable=False),
        sa.Column('software_short_name', sa.String(length=50), nullable=True),
        sa.Column('version_number', sa.String(length=20), nullable=False),
        sa.Column('development_language', sa.String(length=100), nullable=False),
        sa.Column('development_environment', sa.Text(), nullable=True),
        sa.Column('runtime_environment', sa.Text(), nullable=True),
        sa.Column('code_line_count', sa.Integer(), nullable=True),
        sa.Column('functional_description', sa.Text(), nullable=True),
        sa.Column('technical_features', sa.Text(), nullable=True),
        sa.Column('target_domain', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('project_id')
    )
    
    # file_upload 表
    op.create_table(
        'file_upload',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('uploaded_by', sa.UUID(), nullable=False),
        sa.Column('original_name', sa.String(length=255), nullable=False),
        sa.Column('storage_name', sa.String(length=255), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('checksum', sa.String(length=64), nullable=False),
        sa.Column('file_category', sa.String(length=50), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=True),
        sa.Column('processing_status', sa.String(length=20), nullable=False),
        sa.Column('processing_result', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_upload_project_id'), 'file_upload', ['project_id'], unique=False)
    
    # code_bundle 表
    op.create_table(
        'code_bundle',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('copyright_data_id', sa.UUID(), nullable=False),
        sa.Column('upload_id', sa.UUID(), nullable=True),
        sa.Column('original_file_name', sa.String(length=255), nullable=False),
        sa.Column('original_file_size', sa.Integer(), nullable=False),
        sa.Column('total_files', sa.Integer(), nullable=False),
        sa.Column('total_lines', sa.Integer(), nullable=False),
        sa.Column('processed_lines', sa.Integer(), nullable=False),
        sa.Column('pages_data', sa.JSON(), nullable=False),
        sa.Column('language_stats', sa.JSON(), nullable=False),
        sa.Column('has_enough_code', sa.Boolean(), nullable=False),
        sa.Column('warnings', sa.JSON(), nullable=True),
        sa.Column('processed_file_path', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copyright_data_id'], ['copyright_data.id'], ),
        sa.ForeignKeyConstraint(['upload_id'], ['file_upload.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_bundle_copyright_data_id'), 'code_bundle', ['copyright_data_id'], unique=False)
    
    # copyright_manual 表
    op.create_table(
        'copyright_manual',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('copyright_data_id', sa.UUID(), nullable=False),
        sa.Column('template_type', sa.String(length=20), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('content_html', sa.Text(), nullable=True),
        sa.Column('content_json', sa.JSON(), nullable=True),
        sa.Column('word_count', sa.Integer(), nullable=True),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('screenshot_count', sa.Integer(), nullable=False),
        sa.Column('has_toc', sa.Boolean(), nullable=False),
        sa.Column('has_chapters', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copyright_data_id'], ['copyright_data.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copyright_manual_copyright_data_id'), 'copyright_manual', ['copyright_data_id'], unique=False)
    
    # manual_screenshot 表
    op.create_table(
        'manual_screenshot',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('manual_id', sa.UUID(), nullable=False),
        sa.Column('upload_id', sa.UUID(), nullable=False),
        sa.Column('caption', sa.String(length=200), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['manual_id'], ['copyright_manual.id'], ),
        sa.ForeignKeyConstraint(['upload_id'], ['file_upload.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_screenshot_manual_id'), 'manual_screenshot', ['manual_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_screenshot_manual_id'), table_name='manual_screenshot')
    op.drop_table('manual_screenshot')
    op.drop_index(op.f('ix_copyright_manual_copyright_data_id'), table_name='copyright_manual')
    op.drop_table('copyright_manual')
    op.drop_index(op.f('ix_code_bundle_copyright_data_id'), table_name='code_bundle')
    op.drop_table('code_bundle')
    op.drop_index(op.f('ix_file_upload_project_id'), table_name='file_upload')
    op.drop_table('file_upload')
    op.drop_table('copyright_data')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_project_type'), table_name='project')
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
